# Stripe Configuration for different environments and countries
development:
  refresh_url: 'http://localhost:3000/wallet/refresh'
  return_url: 'http://localhost:3000/wallet/success'

staging:
  refresh_url: 'https://staging.ravenboost.com/wallet/refresh'
  return_url: 'https://staging.ravenboost.com/wallet/success'

production:
  refresh_url: 'https://www.ravenboost.com/wallet/refresh'
  return_url: 'https://www.ravenboost.com/wallet/success'

# Supported countries and their specific capabilities
countries:
  # North America
  US:
    name: 'United States'
    capabilities:
      - card_payments
      - transfers
    currency: 'usd'
  CA:
    name: 'Canada'
    capabilities:
      - card_payments
      - transfers
    currency: 'cad'
  MX:
    name: 'Mexico'
    capabilities:
      - card_payments
      - transfers
    currency: 'mxn'

  # Europe
  GB:
    name: 'United Kingdom'
    capabilities:
      - card_payments
      - transfers
    currency: 'gbp'
  FR:
    name: 'France'
    capabilities:
      - card_payments
      - transfers
    currency: 'eur'
  DE:
    name: 'Germany'
    capabilities:
      - card_payments
      - transfers
    currency: 'eur'
  IT:
    name: 'Italy'
    capabilities:
      - card_payments
      - transfers
    currency: 'eur'
  ES:
    name: 'Spain'
    capabilities:
      - card_payments
      - transfers
    currency: 'eur'
  NL:
    name: 'Netherlands'
    capabilities:
      - card_payments
      - transfers
    currency: 'eur'
  BE:
    name: 'Belgium'
    capabilities:
      - card_payments
      - transfers
    currency: 'eur'
  AT:
    name: 'Austria'
    capabilities:
      - card_payments
      - transfers
    currency: 'eur'
  CH:
    name: 'Switzerland'
    capabilities:
      - card_payments
      - transfers
    currency: 'chf'
  SE:
    name: 'Sweden'
    capabilities:
      - card_payments
      - transfers
    currency: 'sek'
  NO:
    name: 'Norway'
    capabilities:
      - card_payments
      - transfers
    currency: 'nok'
  DK:
    name: 'Denmark'
    capabilities:
      - card_payments
      - transfers
    currency: 'dkk'
  FI:
    name: 'Finland'
    capabilities:
      - card_payments
      - transfers
    currency: 'eur'
  IE:
    name: 'Ireland'
    capabilities:
      - card_payments
      - transfers
    currency: 'eur'
  LU:
    name: 'Luxembourg'
    capabilities:
      - card_payments
      - transfers
    currency: 'eur'
  PT:
    name: 'Portugal'
    capabilities:
      - card_payments
      - transfers
    currency: 'eur'

  # Asia-Pacific
  AU:
    name: 'Australia'
    capabilities:
      - card_payments
      - transfers
    currency: 'aud'
  NZ:
    name: 'New Zealand'
    capabilities:
      - card_payments
      - transfers
    currency: 'nzd'
  JP:
    name: 'Japan'
    capabilities:
      - card_payments
      - transfers
    currency: 'jpy'
  SG:
    name: 'Singapore'
    capabilities:
      - card_payments
      - transfers
    currency: 'sgd'
  HK:
    name: 'Hong Kong'
    capabilities:
      - card_payments
      - transfers
    currency: 'hkd'
  MY:
    name: 'Malaysia'
    capabilities:
      - card_payments
      - transfers
    currency: 'myr'
  TH:
    name: 'Thailand'
    capabilities:
      - card_payments
      - transfers
    currency: 'thb'
  PH:
    name: 'Philippines'
    capabilities:
      - card_payments
      - transfers
    currency: 'php'
  IN:
    name: 'India'
    capabilities:
      - card_payments
      - transfers
    currency: 'inr'

  # South America
  BR:
    name: 'Brazil'
    capabilities:
      - card_payments
      - transfers
    currency: 'brl'

# Default capabilities if country not found in the list above
default_capabilities:
  - card_payments
  - transfers
