name: Deploy to EC2

on:
  push:
    branches:
      - main  # Change this to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/github_actions_key
          chmod 600 ~/.ssh/github_actions_key
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/github_actions_key -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            # Initialize rbenv and set PATH
            export PATH="$HOME/.rbenv/shims:$HOME/.rbenv/bin:$PATH"
            eval "$(rbenv init -)"

            # Optional: Source your shell profile to ensure any other environment variables are set
            source ~/.bashrc

            # Debugging information
            echo "Current PATH: $PATH"
            echo "Ruby version: $(ruby -v)"
            echo "Bundler version: $(bundler -v)"
            echo "Rails version: $(rails -v)"
            
            cd /home/ubuntu/boost_backend
            git pull origin main

            # Append 'development' and 'test' to the existing without configuration
            current_without=$(bundle config get without | cut -d ' ' -f 2)
            if [[ "$current_without" != "" ]]; then
              new_without="$current_without development test"
            else
              new_without="development test"
            fi
            bundle config set --local without "$new_without"

            # Install the gems
            bundle install

            # Run database migrations
            RAILS_ENV=production rails db:migrate

            # Restart the Puma service
            sudo systemctl restart puma.service
          EOF


