name: Deploy to EC2

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/github_actions_key
          chmod 600 ~/.ssh/github_actions_key
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/github_actions_key -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            # Initialize rbenv and set PATH
            export PATH="$HOME/.rbenv/shims:$HOME/.rbenv/bin:$PATH"
            eval "$(rbenv init -)"
            # Optional: Source your shell profile to ensure any other environment variables are set
            source ~/.bashrc
            
            cd /home/ubuntu/boost_backend
            git config pull.rebase true  # Set rebase behavior
            git pull origin production 
            # Install the gems
            bundle install
            # Run database migrations
            RAILS_ENV=production rails db:migrate
          EOF


